# Generated by Django 4.0.6 on 2022-08-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charge_market.transaction')),
            ],
            bases=('charge_market.transaction',),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='charge',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='charge_market.transaction')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='charge_market.phonenumber')),
            ],
            bases=('charge_market.transaction',),
        ),
    ]
