# Generated by Django 4.0.6 on 2022-08-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_market', '0002_chargetransaction_rename_charge_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='credit',
            new_name='_credit',
        ),
    ]
