# Generated by Django 4.0.6 on 2022-08-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge_market', '0003_rename_credit_vendor__credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='charge_market.vendor'),
        ),
    ]
