# Generated by Django 4.0.6 on 2022-08-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge_market', '0004_alter_transaction_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selltransaction',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='charge_market.phonenumber'),
        ),
    ]
